### ISSUE TITLE
thread 'thread 'thread 'thread '<unnamed><unnamed><unnamed>' panicked

### ISSUE THREAD

**Issue by aadityakanjolia4** [xavctn/img2table#87] opened 2023-07-26 10:37 UTC
for some pdf , few pages are not extratced and showing this error:

thread 'thread 'thread 'thread '<unnamed><unnamed><unnamed>' panicked at '' panicked at '' panicked at '<unnamed>called `Option::unwrap()` on a `None` valuecalled `Option::unwrap()` on a `None` value' panicked at '', ', called `Option::unwrap()` on a `None` value/home/runner/work/polars/polars/polars/polars-lazy/polars-pipe/src/executors/sinks/joins/cross.rs/home/runner/work/polars/polars/polars/polars-lazy/polars-pipe/src/executors/sinks/joins/cross.rs', ::/home/runner/work/polars/polars/polars/polars-lazy/polars-pipe/src/executors/sinks/joins/cross.rs118118:::1185656:

**Comment by aadityakanjolia4** [comment] 2023-07-26 10:43
for some pdf , few pages are not extratced and showing this error:

thread 'thread 'thread 'thread '<unnamed><unnamed><unnamed>' panicked at '' panicked at '' panicked at '<unnamed>called `Option::unwrap()` on a `None` valuecalled `Option::unwrap()` on a `None` value' panicked at '', ', called `Option::unwrap()` on a `None` value/home/runner/work/polars/polars/polars/polars-lazy/polars-pipe/src/executors/sinks/joins/cross.rs/home/runner/work/polars/polars/polars/polars-lazy/polars-pipe/src/executors/sinks/joins/cross.rs', ::/home/runner/work/polars/polars/polars/polars-lazy/polars-pipe/src/executors/sinks/joins/cross.rs118118:::1185656:

**Comment by xavctn** [comment] 2023-07-30 18:34
Hi,
I will check if I can find the source of the error

**Comment by xavctn** [comment] 2023-08-01 21:17
It might be fixed with the latest version.
Are you able to try to run the latest release on your PDF and report if the error is still happening ?

**Comment by aadityakanjolia4** [comment] 2023-08-02 09:24
> It might be fixed with the latest version. Are you able to try to run the latest release on your PDF and report if the error is still happening ?

no, its showing same error

**Comment by xavctn** [comment] 2023-08-02 09:33
Can you provide one of the document so that I can reproduce the error ?

**Comment by aadityakanjolia4** [comment] 2023-08-02 10:01
> Can you provide one of the document so that I can reproduce the error ?

can you send me your email?

**Comment by xavctn** [comment] 2023-08-02 11:08
xav.canton@gmail.com

**Comment by aadityakanjolia4** [comment] 2023-08-03 06:02
> [xav.canton@gmail.com](mailto:xav.canton@gmail.com)

please check the mail

**Comment by xavctn** [comment] 2023-08-03 11:42
I checked your file and apply some corrections to the code.
Everything should be working as intended right now

**Closed** 2023-08-03 11:43 UTC

**Comment by aadityakanjolia4** [comment] 2023-08-04 10:03
> I checked your file and apply some corrections to the code. Everything should be working as intended right now

that file is is working but there are also few files which are showing same error now also, can you tell me where the problem is?

**Comment by xavctn** [comment] 2023-08-04 10:20
You can send me the other files and I will check

**Comment by aadityakanjolia4** [comment] 2023-08-07 08:12
> You can send me the other files and I will check

I have mailed you

**Comment by aadityakanjolia4** [comment] 2023-08-11 12:18
most of the issue is solved, but a little error is there, please check mail.
